#ifndef PUBLIC_COM_RETURN_RESULTS
#define PUBLIC_COM_RETURN_RESULTS

#define ERR_CODE						0x200
#define MAKE_OWN_FAIL_RESULT(x) MAKE_HRESULT(SEVERITY_ERROR, FACILITY_ITF, ERR_CODE+x)
#define GET_OWN_FAIL_CODE(x) (HRESULT_CODE(x)-ERR_CODE)

#define ERR_CODE_FALSE		0x00
#define ERR_CODE_EMPTY		0X01
#define ERR_CODE_OVERFLOW	0X02
#define ERR_CODE_PARAMETER	0X10
#endif